#!/usr/bin/env node
/**
 * Pipeline gen:api — lê o OpenAPI do app FastAPI (via dump_openapi.py) e gera
 * os tipos TypeScript com openapi-typescript, injetando o cabeçalho AUTO-GENERATED.
 *
 * Fluxo:
 *   1. Roda: python backend/scripts/dump_openapi.py -> JSON determinístico (sort_keys=True)
 *   2. Salva em arquivo temporário
 *   3. Roda: openapi-typescript <tmp> -o <output>
 *   4. Prepend do cabeçalho "AUTO-GENERATED — DO NOT EDIT. Run: npm run gen:api"
 *   5. Limpa o tmp
 *
 * Determinístico: dump_openapi.py usa sort_keys=True → mesmo input = mesmo output byte-a-byte.
 *
 * Uso: node scripts/gen-api.mjs
 * (chamado via npm run gen:api)
 */
import { execFileSync } from 'child_process';
import { writeFileSync, readFileSync, unlinkSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { tmpdir } from 'os';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const REPO_ROOT = join(ROOT, '..');
const OUTPUT = join(ROOT, 'src', 'app', 'api', 'generated', 'openapi-types.ts');
const OPENAPI_JSON = join(ROOT, 'src', 'app', 'api', 'generated', 'openapi.json');
const TMP = join(tmpdir(), `openapi-dump-${process.pid}.json`);

const HEADER_COMMENT = [
  '/**',
  ' * AUTO-GENERATED — DO NOT EDIT. Run: npm run gen:api',
  ' * Source: backend/scripts/dump_openapi.py -> FastAPI app.openapi() (sort_keys=True)',
  ' * Schema: specs/005-api-contract.md v1.1.0',
  ' *',
  ' * Para regenerar:',
  ' *   cd frontend && npm run gen:api',
  ' *',
  ' * Não edite manualmente. Use api/api.types.ts para aliases de domínio.',
  ' */',
  '',
].join('\n');

try {
  // 1. Dump do OpenAPI do backend (determinístico: sort_keys=True)
  console.log('[gen:api] Gerando OpenAPI schema via backend/scripts/dump_openapi.py...');
  const dumpScript = join(REPO_ROOT, 'backend', 'scripts', 'dump_openapi.py');

  const jsonContent = execFileSync('python', [dumpScript], {
    cwd: REPO_ROOT,
    encoding: 'utf-8',
    env: { ...process.env, PYTHONIOENCODING: 'utf-8', PYTHONUTF8: '1' },
  });

  // 2. Salva em arquivo temporário (para openapi-typescript) e materializa o openapi.json
  // gerado na pasta generated/ — usado pelos contract tests para carregar schemas vivos.
  // Usa a mesma string jsonContent (não re-serializa) para preservar o sort_keys/indent
  // determinístico produzido por dump_openapi.py.
  writeFileSync(TMP, jsonContent, 'utf-8');
  writeFileSync(OPENAPI_JSON, jsonContent, 'utf-8');
  console.log(`[gen:api] OpenAPI JSON materializado em ${OPENAPI_JSON}`);

  // 3. Gera tipos TypeScript (usa o binário real, não o wrapper bash do .bin/)
  const openapiTsBin = join(ROOT, 'node_modules', 'openapi-typescript', 'bin', 'cli.js');
  console.log(`[gen:api] Gerando tipos TypeScript em ${OUTPUT}...`);

  execFileSync(
    'node',
    [openapiTsBin, TMP, '-o', OUTPUT],
    { cwd: ROOT, stdio: 'inherit', encoding: 'utf-8' },
  );

  // 4. Prepend do cabeçalho AUTO-GENERATED (openapi-typescript v7 não tem --header-comment)
  const generated = readFileSync(OUTPUT, 'utf-8');
  // Remove o cabeçalho padrão da ferramenta e substitui pelo nosso
  const withoutToolHeader = generated.replace(
    /^\/\*\*\n \* This file was auto-generated by openapi-typescript\.[^\*]*\*\/\n\n?/,
    '',
  );
  writeFileSync(OUTPUT, HEADER_COMMENT + withoutToolHeader, 'utf-8');

  console.log('[gen:api] Tipos gerados com sucesso e cabeçalho AUTO-GENERATED injetado.');
} finally {
  // 5. Limpa o tmp
  if (existsSync(TMP)) {
    unlinkSync(TMP);
  }
}
